name: core
version: 16-2
version-script: |
    # remember to keep version script in sync with "Makefile"
    echo "16-$(cat prime/usr/lib/snapd/info |cut -f2 -d=| sed s/~ubuntu.*// | cut -b1-29)"
summary: snapd runtime environment
description: The core runtime environment for snapd
confinement: strict
type: os
grade: stable

plugs:
  core-support-plug:
    interface: core-support

hooks:
  configure:
    plugs: [core-support-plug]

parts:
  hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
      - shellcheck
      - gawk

  xdg-open:
    source: xdg-open
    plugin: make
    build-packages:
      - gcc
      - pkg-config
      - libglib2.0-dev
